реализована функция преобразования объектов в массив имён
js-tasks-ru/jsbasic-20220519_plower222 pull request #2
Opened 2022-05-31 15:44 UTC by plower222

2022-05-31 15:45 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-05-31 15:58 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-05-31 16:23 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-05-31 20:16 UTC, SinimaWath requested changes

2022-05-31 20:16 UTC, SinimaWath commented on 3-module/3-task/index.js
> +  }
Немного сложный код. Давай тут попробуем map

2022-06-01 16:38 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-06-01 17:06 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-06-01 20:24 UTC, SinimaWath approved these changes

2022-06-01 20:24 UTC, merged