Реализована карусель с доработками
js-tasks-ru/jsbasic-20220519_plower222 pull request #6
Opened 2022-06-18 08:16 UTC by plower222

2022-06-19 09:38 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-06-19 15:49 UTC, SinimaWath requested changes

2022-06-19 15:49 UTC, SinimaWath commented on 6-module/3-task/index.js
> +    let elem = this.slides;
А зачем тут создаешь временную переменную elem? Давай без нее

2022-06-19 15:49 UTC, SinimaWath commented on 6-module/3-task/index.js
> +    elem.forEach(element => {
Давой попробуем: `let templateCards = this.slides.map().join('')`

2022-06-19 15:49 UTC, SinimaWath commented on 6-module/3-task/index.js
> +        });
Не нужная подписка на событие

2022-06-19 16:38 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-06-19 16:54 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-06-20 14:08 UTC, SinimaWath approved these changes

2022-06-20 14:09 UTC, merged