модальное окно. промежуточный вариант
js-tasks-ru/jsbasic-20220519_plower222 pull request #7
Opened 2022-06-21 08:51 UTC by plower222

2022-06-21 08:53 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-06-21 09:31 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-06-22 09:20 UTC, SinimaWath requested changes

2022-06-22 09:20 UTC, SinimaWath commented on 7-module/2-task/index.js
> +    });
А зачем клик по модальному окну, у тебя закрывается модальное окно?

2022-06-22 09:20 UTC, SinimaWath commented on 7-module/2-task/index.js
> +  close() {
По условию задачи - публичный метод close - должен закрывать модальное окно. А в твоей реализации он подписывается на обновления.

Надо разделить close и подписки на события.

2022-06-22 14:34 UTC, plower222 commented on 7-module/2-task/index.js
> +    });
Делал, чтобы модальное окно пропадало при нажатии вне него

2022-06-22 15:24 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-06-22 15:36 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-06-22 17:36 UTC, SinimaWath approved these changes

2022-06-22 17:36 UTC, SinimaWath commented
не все задачи решены, которые добавил. Но в этих все ок

2022-06-22 17:36 UTC, merged