реализован пошаговый слайдер часть 2
js-tasks-ru/jsbasic-20220519_plower222 pull request #8
Opened 2022-06-22 17:56 UTC by plower222

2022-06-22 18:01 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-06-24 16:26 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-06-24 21:02 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-06-25 10:15 UTC, SinimaWath requested changes

2022-06-25 10:15 UTC, SinimaWath commented on 8-module/1-task/index.js
> +    let initialTopCoord = this.elem.getBoundingClientRect().top + window.pageYOffset;
в это задаче initialTopCoord = необхожимо высчитывать только один раз:
```
if (!this.initialTopCoord) {
  this. initialTopCoord = ....
}
```

2022-06-25 10:15 UTC, SinimaWath commented on 8-module/2-task/index.js
> +    let filteredMenu = this.tempalate().querySelector('.products-grid__inner');
Надо фильтры сохранять и мержить, к примеру вот так:
`this.filters = Object.assign(this.filters, filters)`

2022-06-25 10:15 UTC, SinimaWath commented on 8-module/2-task/index.js
> +    }
Давай заменим на: `this.filters = Object.assign(this.filters, filters)`

2022-06-25 10:15 UTC, SinimaWath commented on 8-module/2-task/index.js
> +      let temp = arrayTemp.filter(item => !item.product.hasOwnProperty('nuts') || item.product.noNuts === false);
Тут нет смысла во временной переменной temp и в остальных местах тоже:
`arrayTemp = arrayTemp.filter(item => !item.product.hasOwnProperty('nuts') || item.product.noNuts === false)`

2022-06-25 10:15 UTC, SinimaWath commented on 8-module/2-task/index.js
> +    let productsGridInner = document.querySelector('.products-grid__inner');
Почему из document? у тебя же есть контейнер

2022-06-27 06:10 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-06-28 12:28 UTC, SinimaWath approved these changes

2022-06-28 12:28 UTC, merged